import petar
import numpy as np
import matplotlib.pyplot as plt
import astropy.units as u
import matplotlib.colors as colors
from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable
from matplotlib import gridspec
from astropy.table import Table

import astropy.coordinates as coord
from astropy.coordinates import Galactocentric, ICRS, CartesianRepresentation, CartesianDifferential
from astropy.coordinates import SkyCoord

import astropy.units as u
import numpy as np
import gala.coordinates as gc
import gala.dynamics as gd
import gala.potential as gp
from gala.dynamics import mockstream as ms

from gala.units import galactic

from mpl_toolkits.axes_grid1 import make_axes_locatable
import matplotlib.colors as mcolors

import astropy.constants as const
from streamframe import StreamFrame
from scipy.stats import binned_statistic
import scipy.stats as stats
from scipy.optimize import curve_fit
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize
from matplotlib.colors import LinearSegmentedColormap

from scipy.stats import binom
from tqdm import tqdm

from scipy.ndimage import gaussian_filter1d

 
##### FUNCTIONS
def define_time_cmap():
    colors=["#212738","#4D3041","#79394A","#994250","#B24B54","#C55756","#D26A54","#DC8051","#E5974D","#EDAE49"]
    colors.reverse()
    time_cmap = LinearSegmentedColormap.from_list('time_cmap', colors)
    return time_cmap

def define_simcolors():
    lm_colors = ["#2D3047","#246569","#1B998B","#8DCB87"] # increasing diffuseness
    hm_colors = ["#BB333C", "#E84855","#FF9B71","#FFCC7A"]#,"#FFE57E"] # same; densest to most diffuse. 

    simcolors = [lm_colors[0],hm_colors[0],lm_colors[1],hm_colors[1],lm_colors[2],hm_colors[2],lm_colors[3],hm_colors[3]] * 3
    return lm_colors, hm_colors, simcolors


class extended_grid_info():
    """
    initialize a class with attributes
    for the paths to simulation data, 
    apocenters of each orbit
    thin stream ages according to vedant
    init displacements
    most info comes from /data/init_displacements.txt
    """
    def __init__(self, scratch=True):
        if scratch==True:
            base_path = '/n/netscratch/conroy_lab/Lab/amphillips/extended_grid/'
        if scratch==False:
            base_path = '/n/holystore01/LABS/conroy_lab/Lab/amphillips/extended_grid/'
            print("!!! STUFF DOES NOT LIVE IN STORAGE YET !!!")
            return

        self.base_path = base_path

        self.gd1_dir = self.base_path+"gd1/"
        self.pa5_dir = self.base_path+"pal5/"
        self.aau_dir = self.base_path+"aau/"
        self.c19_dir = self.base_path+"c19/"
        self.m3_dir = self.base_path+"m3/"
        self.jet_dir = self.base_path+"jet/"

        rvirs = ['0.75', '1.5', '3','6']

        self.gd1_lm_paths = [self.gd1_dir+"lm/"+rvir+"/" for rvir in rvirs]
        self.pa5_lm_paths = [self.pa5_dir+"lm/"+rvir+"/" for rvir in rvirs]
        self.aau_lm_paths = [self.aau_dir+"lm/"+rvir+"/" for rvir in rvirs]
        self.c19_lm_paths = [self.c19_dir+"lm/"+rvir+"/" for rvir in rvirs]
        self.jet_lm_paths = [self.jet_dir+"lm/"+rvir+"/" for rvir in rvirs]
        self.m3_lm_paths = [self.m3_dir+"lm/"+rvir+"/" for rvir in rvirs]

        self.gd1_hm_paths = [self.gd1_dir+"hm/"+rvir+"/" for rvir in rvirs]
        self.pa5_hm_paths = [self.pa5_dir+"hm/"+rvir+"/" for rvir in rvirs]
        self.aau_hm_paths = [self.aau_dir+"hm/"+rvir+"/" for rvir in rvirs]
        self.c19_hm_paths = [self.c19_dir+"hm/"+rvir+"/" for rvir in rvirs]
        self.jet_hm_paths = [self.jet_dir+"hm/"+rvir+"/" for rvir in rvirs]
        self.m3_hm_paths = [self.m3_dir+"hm/"+rvir+"/" for rvir in rvirs]


        ### also need to do circular orbits. 
        base_path_old = "/n/holystore01/LABS/conroy_lab/Lab/amphillips/finished_grid/"
        path0 = base_path_old+"optimized_dense_sims/0_circ_rvir0.75_lm/" # unfinished
        path1 = base_path_old+"optimized_dense_sims/1_circ_rvir0.75_hm/"  # done
        path2 = base_path_old+"2_circ_rvir1.5_lm/"
        path3 = base_path_old+"3_circ_rvir1.5_hm/"
        path4 = base_path_old+"4_circ_rvir3_lm/"
        path5 = base_path_old+"5_circ_rvir3_hm/"
        path6 = base_path_old+"6_circ_rvir6_lm/"
        path7 = base_path_old+"7_circ_rvir6_hm/"     

        self.circ_lm_paths = [path0, path2, path4, path6]
        self.circ_hm_paths = [path1, path3, path5, path7]


        ### would also like apocenters and stream ages -- taken from data/init_displacements.txt (generated by get_init_displacements.py)
        # will be able to use these for indexing and outlier rejection. 
        self.aau_age = 2620 # Myr
        self.aau_apo = 39.75165840315315 # kpc
        self.aau_init_displacement = [-10146.00826766252976085525,8919.85851260721756261773,-24103.22041046262529562227,103.04154947248773055435,79.06293437892136921619,127.13180750768465543388]

        self.c19_age = 3670 # Myr
        self.c19_apo = 22.37095916931149 # kpc
        self.c19_init_displacement = [12417.38173580253715044819,-18474.56735762703829095699,-1361.38862424165904485562,-5.31601757529761442811,-9.00030612586674827469,147.27681047797699420698]
        
        self.gd1_age = 2700 # Myr
        self.gd1_apo = 25.05610863789965 # kpc
        self.gd1_init_displacement = [101.24414852604452619289,16450.78926659073476912454,-2019.90591424317676683131,-162.30565892719911857967,90.69437329262960645337,134.06063942732188820628]


        self.jet_age = 3950 # Myr
        self.jet_apo = 34.960302575800554 # kpc  
        self.jet_init_displacement = [4260.60002970255027321400,-4299.63916052530657907482,-14178.84863869313085160684,74.33606358822831339239,252.25314609744174276784,-52.12315522407579493347]

        self.m3_apo = 23.224619245545487
        self.m3_age = 2360
        self.m3_init_displacement = [-879.12379288676629585098,7660.03420407489829813130,13384.68144932837276428472,109.58335588916739311571,-47.69100718430096463862,-143.56484318030865665605]


        self.pa5_apo = 16.525918308666228
        self.pa5_age = 3570
        self.pa5_init_displacement = [3984.70438680068355097319,4551.73882141487047192641,-13226.39622530415363144130,113.09106691651193443704,-70.74982682771090480855,88.07032224724790125947]


        self.circ_init_displacement = np.array([20.0,0.0,0.0,0.0,197.61111175113643,0.0])  # <-- comes from computing vcirc in mwp2014 at 20 kpc
        self.circ_age = 10000
        self.circ_apo = 20.0

    def retrieve_sim_info(self, orbit, stellar_pop, rvir_index, copy):
        """
        rvir_index goes 
        from 0-3 and means 0.75, 1.5, 3, 6 pc"""
        if orbit=='gd1':
            age = self.gd1_age
            init_displacement = self.gd1_init_displacement
            apo = self.gd1_apo
            if stellar_pop=='lm':
                base_paths = self.gd1_lm_paths
            if stellar_pop=='hm':
                base_paths = self.gd1_hm_paths
        if orbit=='pa5':
            age = self.pa5_age
            init_displacement = self.pa5_init_displacement
            apo = self.pa5_apo
            if stellar_pop=='lm':
                base_paths = self.pa5_lm_paths
            if stellar_pop=='hm':
                base_paths = self.pa5_hm_paths
        if orbit=='c19':
            age = self.c19_age
            init_displacement = self.c19_init_displacement
            apo = self.c19_apo
            if stellar_pop=='lm':
                base_paths = self.c19_lm_paths
            if stellar_pop=='hm':
                base_paths = self.c19_hm_paths
        if orbit=='aau':
            age = self.aau_age
            init_displacement = self.aau_init_displacement
            apo = self.aau_apo
            if stellar_pop=='lm':
                base_paths = self.aau_lm_paths
            if stellar_pop=='hm':
                base_paths = self.aau_hm_paths
        if orbit=='jet':
            age = self.jet_age
            init_displacement = self.jet_init_displacement
            apo = self.jet_apo
            if stellar_pop=='lm':
                base_paths = self.jet_lm_paths
            if stellar_pop=='hm':
                base_paths = self.jet_hm_paths
        if orbit=='m3':
            age = self.m3_age
            init_displacement = self.m3_init_displacement
            apo = self.m3_apo
            if stellar_pop=='lm':
                base_paths = self.m3_lm_paths
            if stellar_pop=='hm':
                base_paths = self.m3_hm_paths

        if orbit=='circ':
            init_displacement = self.circ_init_displacement
            age = int(10000 * 10)
            apo = self.circ_apo
            if stellar_pop == 'lm':
                base_paths = self.circ_lm_paths
            if stellar_pop=='hm':
                base_paths = self.circ_hm_paths
        
        path_to_correct_rvir = base_paths[rvir_index]
        
        if orbit=='circ':
            path = path_to_correct_rvir #<-- in this case i have only one realization
        else:
            path = path_to_correct_rvir+"%i/"%copy #<-- select a realization from the copies in the grid. 

        return path, apo, age, init_displacement

def define_paths_scratch(): #<-- LEFTOVER FROM OLD GRID
    """
    alt path function to call from scratch directories. 
    """
    ph = "/n/netscratch/conroy_lab/Lab/amphillips/finished_grid/"
    path0 = ph+"0_circ_rvir0.75_lm/"
    path1 = ph+"1_circ_rvir0.75_hm/"
    path2= ""
    path3=""
    path4=""
    path5=""
    path6=ph+"6_circ_rvir6_lm/"
    path7 = ph+"7_circ_rvir6_hm/"
    path8 = ph+"8_gd1_rvir0.75_lm/"
    path9=ph+"9_gd1_rvir0.75_hm/"
    path10=""
    path11=""
    path12=""
    path13=""
    path14=ph+"14_gd1_rvir6_lm/"
    path15=ph+"15_gd1_rvir6_hm/"
    path16=ph+"16_pal5_rvir0.75_lm/"
    path17=ph+"17_pal5_rvir0.75_hm/"
    path18=""
    path19=""
    path20=""
    path21=""
    path22=ph+"22_pal5_rvir6_lm/"
    path23=ph+"23_pal5_rvir6_hm/"
    
    paths = [path0,path1,path2,path3,path4,path5,path6,path7,
             path8,path9,path10,path11,path12,path13,path14,path15,
             path16,path17,path18,path19,path20,path21,path22,path23]

    return paths

def define_paths(): #<-- LEFTOVER FROM OLD GRID
    ph = "/n/holystore01/LABS/conroy_lab/Lab/amphillips/finished_grid/"

    path0 = ph+"optimized_dense_sims/0_circ_rvir0.75_lm/" # unfinished
    # path0 = "/n/netscratch/conroy_lab/Lab/amphillips/small_grid/optimize_dense_sims_testing/0_circ_rvir0.75_lm/"
    path1 = ph+"optimized_dense_sims/1_circ_rvir0.75_hm/"  # done
    path2 = ph+"2_circ_rvir1.5_lm/"
    path3 = ph+"3_circ_rvir1.5_hm/"
    path4 = ph+"4_circ_rvir3_lm/"
    path5 = ph+"5_circ_rvir3_hm/"
    path6 = ph+"6_circ_rvir6_lm/"
    path7 = ph+"7_circ_rvir6_hm/"

    path8 = ph+"optimized_dense_sims/8_gd1_rvir0.75_lm/"  # done
    path9 = ph+"optimized_dense_sims/9_gd1_rvir0.75_hm/" # done
    # path10 = ph+"10_gd1_rvir1.5_lm/" #<-- this sim has particles deleted; unphysical
    path10 = "/n/holystore01/LABS/conroy_lab/Lab/amphillips/finished_grid/10_copies_successful/0/" # <--sucsessful sim w no particle deletions. 

    path11 = ph+"11_gd1_rvir1.5_hm/"
    path12 = ph+"12_gd1_rvir3_lm/"
    path13 = ph+"13_gd1_rvir3_hm/"
    path14 = ph+"14_gd1_rvir6_lm/"
    path15 = ph+"15_gd1_rvir6_hm/"

    path16 = ph+"optimized_dense_sims/16_pal5_rvir0.75_lm/" # done. 
    path17 = ph+"optimized_dense_sims/17_pal5_rvir0.75_hm/" # done. 
    path18 = ph+"18_pal5_rvir1.5_lm/"
    path19 = ph+"19_pal5_rvir1.5_hm/"
    path20 = ph+"20_pal5_rvir3_lm/"
    path21 = ph+"21_pal5_rvir3_hm/"
    path22 = ph+"22_pal5_rvir6_lm/"
    path23 = ph+"23_pal5_rvir6_hm/"

    paths = [path0,path1,path2,path3,path4,path5,path6,path7,
             path8,path9,path10,path11,path12,path13,path14,path15,
             path16,path17,path18,path19,path20,path21,path22,path23]

    return paths


def define_init_displacements(): #<-- LEFTOVER FROM OLD GRID
    """
    returns a list of initial displacements in kpc, km/s
    for the main grid of petar simulations
    """
    id_circ=np.array([20.0,0.0,0.0,0.0,197.61111175113643,0.0])

    init_pos = np.array([-14680.175269960177, -18049.00342055592, -3355.258112269282]) * u.pc.to(u.kpc)
    init_vel = np.array([126.94017915235732, -33.56076783776999, 112.93136486685516]) # km/s
    id_gd1 = np.concatenate([init_pos, init_vel])


    init_pos_pal5 = np.array([13536.852506889449, -3328.304203161837, 5478.0923546972035]) * u.pc.to(u.kpc)
    init_vel_pal5 = np.array([119.95920838380918, -89.0209982268969, -88.31131556786855]) # km/s
    id_pal5 = np.concatenate([init_pos_pal5, init_vel_pal5])


    init_displacements = [id_circ]*8 + [id_gd1]*8 + [id_pal5]*8

    return init_displacements

def define_apocenters(): #<-- LEFTOVER FROM OLD GRID
    """
    these numbers come from the notebook
    1_table_and_context.ipynb
    """
    circ_apocenter = 20 # kpc
    gd1_apocenter = 27.58821821 # from Gala integration
    pal5_apocenter =  18.55466194 # from Gala integration
    apocenters = [circ_apocenter] * 8 + [gd1_apocenter] * 8 + [pal5_apocenter] * 8
    return apocenters


def get_tdis_tplot(paths, verbose=False): #<-- LEFTOVER FROM OLD GRID
    ##### dissolution and plotting times
    dissolution_times = []
    plotting_times_peri = []
    plotting_times_apo = []

    circ_bools = [True]*8 + [False]*16
    for n, path in enumerate(paths):
        circ_bool = circ_bools[n]
        if n==10: # manually do sim 10, which has time snaps only every 10 Myr
            tidal = load_tidal(path)
            bound_times = tidal.time[tidal.n>=100]
            tdis = int(max(bound_times))

            core = petar.Core(interrupt_mode='bse', external_mode='galpy')
            core.loadtxt(path+"data.core")
            x,y,z = core.pos.T
            r = np.sqrt(x**2 + y**2 + z**2)

            i_dis = int(tdis/10)
            r_times_to_check = tidal.time[i_dis-50:i_dis].astype(int) 
            r_inds_to_check = r_times_to_check / 10
            r_inds_to_check = r_inds_to_check.astype(int) 
            rs_to_check = r[r_inds_to_check]

            min_inds, min_vals = find_minima(rs_to_check)
            times_at_minimum = r_times_to_check[min_inds]
            inds_at_minimum = r_inds_to_check[min_inds] 

            max_inds, max_vals = find_maxima(rs_to_check)
            times_at_maximum = r_times_to_check[max_inds]
            inds_at_maximum = r_inds_to_check[max_inds]

            tplot_p = int(max(times_at_minimum))
            tplot_a = int(max(times_at_maximum))     


        else:
            tdis, tplot_p, tplot_a = find_dissolution_plotting_times(path, circ=circ_bool)
        # print("found times...appending...")
        dissolution_times.append(tdis)
        plotting_times_peri.append(tplot_p)
        plotting_times_apo.append(tplot_a)
        if verbose==True:
            print(n, tdis, tplot_p, tplot_a) 

    return dissolution_times, plotting_times_peri, plotting_times_apo


# LEFTOVER FROM ~/stream_velocity_structures; keeping around in case 
# i make escaper dictionaries for the new grid., same deal with match_escape_times/properties
def unpack_escaper_dict(escaper_dict_dedup, return_vectors=False): #<-- LEFTOVER FROM OLD GRID
    # unpacking the de-duplicated dictionary:

    tdis = escaper_dict_dedup["tdis"]
    escape_times = np.array([])
    velocities_after = np.array([])
    velocities_before = np.array([])

    positions_after = np.array([])
    

    pre_ejection_system_masses = np.array([])
    post_ejection_system_masses = np.array([])

    system_type_flags_after = np.array([])
    system_type_flags_before = np.array([])

    vel_vectors_after = []# np.array([])
    pos_vectors_after = []

    for ID in tqdm(escaper_dict_dedup.keys()):
        if type(ID)==str:
            continue # avoid first key which will be "t_esc"

        id_dict = escaper_dict_dedup[ID]

        tesc = id_dict['t_esc']

        # if tesc not in t_corebad: # only include things where the core positions are valid.
        escape_times = np.append(escape_times, tesc)

        dict_before = id_dict["before_escape"]
        dict_after = id_dict["after_escape"]

        ##### ejection velocities -- _after_ the time of ejection!!!
        x,y,z = dict_after['pos_progframe'] 
        r = np.sqrt(x**2 + y**2 + z**2)
        positions_after = np.append(positions_after, r)

        vx, vy, vz = dict_after['vel_progframe'] * (u.pc/u.Myr).to(u.km/u.s)
        v = np.sqrt(vx**2 + vy**2 + vz**2)
        velocities_after = np.append(velocities_after, v)

        #### potential previous bug... this used to be below the before lines,
        # so vel_vectors_after was actually giving me velocities before ejection...
        # not sure how much it will matter. 
        if return_vectors==True:
            vel_vector_after = np.array([vx, vy, vz]) #in km/s
            vel_vectors_after.append(vel_vector_after)
            pos_vectors_after.append(np.array([x,y,z])) # in pc

        ### might also want before stuff... 
        vx, vy, vz = dict_before['vel_progframe'] * (u.pc/u.Myr).to(u.km/u.s)
        v = np.sqrt(vx**2 + vy**2 + vz**2)
        velocities_before = np.append(velocities_before, v)

        
        system_mass_before = dict_before['mass']
        pre_ejection_system_masses = np.append(pre_ejection_system_masses, system_mass_before)
        
        system_mass_after = dict_after['mass']
        post_ejection_system_masses = np.append(post_ejection_system_masses, system_mass_after)

        # get the system flags post ejection....
        system_type_after = dict_after['system_flag']
        system_type_flags_after = np.append(system_type_flags_after, system_type_after)

        system_type_before = dict_before['system_flag']
        system_type_flags_before = np.append(system_type_flags_before, system_type_before)
    
    vel_vectors_after = np.array(vel_vectors_after)
    pos_vectors_after = np.array(pos_vectors_after)

    return tdis, escape_times, velocities_after, velocities_before, positions_after, pre_ejection_system_masses, post_ejection_system_masses, system_type_flags_after, system_type_flags_before, vel_vectors_after, pos_vectors_after

def match_escape_times(IDs, properties, escaperdict):
    """
    a common example would be providing something like
    all_particles.id, coords['phi1'] as IDs, properties <- matched on ID, then
    escaper_dict_dedup as escaperdict. 
    which would return ID-matched (phi1, t_esc)
    """
    id_to_property = {ID:prop for ID, prop in zip(IDs, properties)} # create a mapping between ids and properties
    ids_in_dict = np.array(list(escaperdict.keys()))[1:] # escaperdict is the mapping between ids with escape times and escaper properties
    
    # reorder the properties to match the escaper dict
    reordered_properties = np.array([id_to_property[ID] for ID in ids_in_dict if ID in ids_in_dict]) # note some IDs won't have escape times due to merger-related ID disappearances. the if statement handles this case so that i can iterate through this dictionary at any time. 
    t_esc = np.array([escaperdict[ID]['t_esc'] for ID in ids_in_dict]) # perform the match! 
    
    return reordered_properties, t_esc

def match_escape_properties(IDs, properties, escaperIDs): ##, escaperproperties):
    """
    more general-purpose than above, and potentially less repetative. 
    here I have escaperIDs which is something like IDs_in_dict that is ID matched to escaperproperties,
    and IDs which is matched to properties. return reordered_properties, now ID matched to escaperproperties
    """
    id_to_property = {ID:prop for ID, prop in zip(IDs, properties)} # create a mapping between ids and properties
    # id_to_escaperproperty = {ID:prop for ID, prop in zip(escaperIDs, escaperproperties)}
    reordered_properties = np.array([id_to_property[ID] for ID in escaperIDs if ID in IDs]) # originally did if ID in escaperIDs but I think this is actually what I want (if ID is the the list of ID/properties I'm reordering.)
    return reordered_properties 

def compute_E_Lz(pos, vel, phi, core_pos, core_vel, mwp):
    """
    would be nice if everything had astropy units. 
    position, velocity, potential @ each particle location, 
    progenitor phase space position.
    """
    x, y, z = pos.T
    vx, vy, vz = vel.T

    xc, yc, zc = core_pos
    vxc, vyc, vzc = core_vel

    # particle  energy
    v2 = vx**2 + vy**2 + vz**2
    E = 0.5 * v2 + phi

    v2_core = vxc**2 + vyc**2 + vzc**2
    phi_core = mwp(gd.PhaseSpacePosition(core_pos, core_vel))
    E_core = 0.5 * v2_core + phi_core

    Lz = x * vy - y * vx # z component of r x v cross product. 
    Lz_core = xc * vyc - yc * vxc

    dE = E - E_core
    dLz = Lz - Lz_core

    return dE, dLz

def calc_P(a, Mtot):
    """
    period from semimajor axis, make the inputs astropy unit quantities
    """
    P = 2*np.pi * np.sqrt((a**3)/(const.G * Mtot))
    return P

def phase_fold(t, porb, t0=0):
    return ((t-t0)%porb)/porb

def calc_amplitude(binary,inclination=np.pi/2):
    """
    calculate the velocity amplitude
    in m/s for a petar binary object assuming some inclination
    (sin(i) = 1)
    """
    Mtot = (binary.mass * u.Msun)#.value
    M2 = min([binary.p1.mass, binary.p2.mass]) * u.Msun

    a = (binary.semi * u.pc).to(u.m)#.value
    e = binary.ecc
    P = calc_P(a, Mtot).to(u.s)

    a1 = (M2/Mtot) * a

    num = 2*np.pi*a1.value *np.sin(inclination)# nominally this would include sin(i)
    denom = P.value * np.sqrt(1-(e**2))
    K = num/denom # velocity semiamplitude - multiply by 2 for full amplitude.
    return K #2*K

def integrate_prog_orbit(init_displacement, steps=10000, dt = 1*u.Myr):
    pos0 = init_displacement[:3] * u.kpc 
    vel0 = init_displacement[3:] * u.km/u.s
    w0 = gd.PhaseSpacePosition(pos0, vel0)
    mwp = gp.BovyMWPotential2014(units=galactic)
    H = gp.Hamiltonian(mwp)
    orbit = H.integrate_orbit(w0, dt=dt, n_steps = steps)
    return orbit

def Trad_firstApo(orbit):
    r = np.sqrt(orbit.pos.x**2 + orbit.pos.y**2 + orbit.pos.z**2).to(u.kpc).value
    max_inds, max_vals = find_maxima(r)
    Trad = np.median(np.diff(max_inds))
    firstApo = max_inds[0]
    return Trad, firstApo

def prog_position(init_displacement, i):
    """
    integrate the progenitor orbit up to this point
    init displacement should be in kpc, **km/s (not with astropy units)
    using Gala and the Bovy2014 milky way potential.
    returns (x, y, z, vx, vy, vz) in kpc, km/s
    """
    pos0 = init_displacement[:3] * u.kpc 
    vel0 = init_displacement[3:] * u.km/u.s
    w0 = gd.PhaseSpacePosition(pos0, vel0)
    mwp = gp.BovyMWPotential2014(units=galactic)
    H = gp.Hamiltonian(mwp)
    int_time = i
    dt = 1
    orbit = H.integrate_orbit(w0, dt=dt, n_steps = int_time/dt)

    x = orbit.pos.x[-1].to(u.kpc)
    y = orbit.pos.y[-1].to(u.kpc)
    z = orbit.pos.z[-1].to(u.kpc)
    vx = orbit.vel.d_x[-1].to(u.km/u.s)
    vy = orbit.vel.d_y[-1].to(u.km/u.s)
    vz = orbit.vel.d_z[-1].to(u.km/u.s)
    return np.array([x.value, y.value, z.value, vx.value, vy.value, vz.value])

def load_particle(path, i, interrupt="bse",file_naming_convention="every integer"):
    """
    CAUTION! 
    works only for loading from
    an all particles file, e.g.,
    data.0
    for data.0.binary, use petar.Binary()
    and for data.0.single, use petar.Particle() 
    without skiprows=1 in .loadtxt()
    """
    if file_naming_convention=="every integer":
        file = path+"data."+str(i)
    if file_naming_convention=="every 10":
        file = path+"data."+str(int(i/10))
    particle = petar.Particle(interrupt_mode=interrupt, external_mode='galpy')
    particle.loadtxt(file, skiprows=1)
    return particle

def load_core(path, interrupt='bse'):
    core = petar.Core(interrupt_mode=interrupt, external_mode='galpy')
    core.loadtxt(path+"data.core")
    return core

def load_tidal(path):
    tidal = petar.external.Tidal()
    tidal.loadtxt(path+"data.tidal")
    return tidal

def fix_core_vel(core):
    """
    differentiate the core position to get the "correct" core velocity. 
    FOR NOW, ONLY WORKS WHEN THE OUTPUT CADENCE IS 1 MYR!!

    returns corrected core velocity (w/o astropy units) in pc/Myr
    """
    core_x, core_y, core_z = core.pos.T * u.pc
    # core_vx, core_vy, core_vz = core.vel.T * u.pc/u.Myr
    times = core.time * u.Myr
    core_dx_dt = np.gradient(core_x, times) # it's giving rigorous. 
    core_dy_dt = np.gradient(core_y, times)
    core_dz_dt = np.gradient(core_z, times)

    core_vel_corrected = np.array([
        core_dx_dt.to(u.pc/u.Myr).value, core_dy_dt.to(u.pc/u.Myr).value, core_dz_dt.to(u.pc/u.Myr).value
    ]).T   

    return core_vel_corrected

def correct_core(core):
    core_pos = core.pos *u.pc
    core_t = core.time*u.Myr
    core_x, core_y, core_z = core.pos.T * u.pc
    core_dx_dt = np.gradient(core_x, core_t)
    core_dy_dt = np.gradient(core_y, core_t)
    core_dz_dt = np.gradient(core_z, core_t)
    core_vel_corrected = np.array([
        core_dx_dt.to(u.pc/u.Myr), 
        core_dy_dt.to(u.pc/u.Myr), 
        core_dz_dt.to(u.pc/u.Myr)
    ]).T

    return core_pos, core_vel_corrected


def is_dissolved(path, i, threshold=100, interrupt="bse"):
    """
    check whether the simulated cluster located at path
    has dissolved at timestep i
    dissolved is defined as fewer than [threshold] stars
    within the tidal radius.
    """
    # load tidal data
    tidal = load_tidal(path)
    n_bound = int(tidal.n[i])
    
    if n_bound<threshold:
        return True
    else:
        return False

def load_coords_v2(path, i, 
                    core=None,
                    tdis_estimate = 3000, 
                    load_all=True, load_singles=True, load_binaries=True,
                    correct_core_vel=True,
                    check_dissolved=True,
                    use_core=True,
                    init_displacement=None,
                    interrupt="bse", # in case I run a sim with no stellar evolution...
                    file_index=None, # in case indexing is different ! ! ! 
                    tdis_estimate_index=None
                    ):
    """
    load stream frame coordinates using jake's package
    path is a path to petar output files directory
    i is the output number we care about
    return all particles and return all single particles lets you return those 
    petar objects as well as their stream coordinates
    returns: [all_particles], binaries, [singles], coords, single_coords, binary_coords
    """

    if file_index==None:
        file_i = i
        tdis_i = tdis_estimate
    else:
        file_i = file_index
        tdis_i = tdis_estimate_index

    file = path+"data."+str(file_index)

    if check_dissolved: ##### OPTION TO CHECK IF THE CLUSTER IS DISSOLVED AND IF SO NOT TO USE THE CORE FILE. 
        if core is None:
            raise BaseException("pass a core object as core=[core]")
        dis = is_dissolved(path, file_i, interrupt=interrupt) # threshold==100

        if dis==False:
            ### if the cluster is not dissolved, use the current core position to do the xform
            if correct_core_vel==True:
                corrected_core_vel = fix_core_vel(core) # avoid spurious jumps
            if correct_core_vel==False:
                corrected_core_vel = core.vel

            core_pos = core.pos[file_i] * u.pc.to(u.kpc) # dimensionless core position in kpc
            core_vel = corrected_core_vel[file_i] * (u.pc/u.Myr).to(u.kpc/u.Myr) # dimensionless core velocity in kpc/myr
            core_w_jake_units = np.hstack([core_pos, core_vel])
            prog_w_jake_units = core_w_jake_units


        if dis==True: # if dissolved, option to use progenitor or use last core position
            # if the cluster _is_ dissolved, integrate the core from estimated dissolution
            # time to now
            if tdis_estimate is None:
                raise BaseException("ENTER AN ESTIMATED DISSOLUTION TIME!")


            core_pos = core.pos[tdis_i] * u.pc.to(u.kpc) # dimensionless core position in kpc
            if correct_core_vel==True:
                corrected_core_vel = fix_core_vel(core) # avoid spurious
            if correct_core_vel==False:
                corrected_core_vel = core.vel

            core_vel = corrected_core_vel[tdis_i] * (u.pc/u.Myr).to(u.km/u.s) # dimensionless core velocity in kpc/myr

            # use prog_position function to integrate from final core position to now
            ### note prog_position requires dimensionless init_displacement in kpc, km/s
            new_init_displacement = np.hstack([core_pos, core_vel])
            time_to_integrate = int(i-tdis_estimate) #<-- refers to simulation time not output index
            prog_w = prog_position(init_displacement=new_init_displacement, i=time_to_integrate) # <-- sim time not file index.

            # transform to jake units
            prog_pos = prog_w[:3] * (u.kpc)
            prog_vel = prog_w[3:] * (u.km/u.s)
            # concatenate. 
            prog_w_jake_units = np.hstack([
                prog_pos.value, prog_vel.to(u.kpc/u.Myr).value
            ]) 

    else: #### if not check_dissolved, then just integrate from the core position at the estimated dissolution time. 
        
        if use_core==True: # option 1 is to use the core position at some estimated tdis
            if core is None:
                raise BaseException("pass a core object as core=[core]")
            if tdis_estimate is None:
                raise BaseException("ENTER AN ESTIMATED DISSOLUTION TIME!")
            
            
            core_pos = core.pos[tdis_i] * u.pc.to(u.kpc) # dimensionless core position in kpc
            if correct_core_vel==True:
                corrected_core_vel = fix_core_vel(core) # avoid spurious
            if correct_core_vel==False:
                corrected_core_vel = core.vel

            core_vel = corrected_core_vel[tdis_i] * (u.pc/u.Myr).to(u.km/u.s) # dimensionless core velocity in kpc/myr

            # use prog_position function to integrate from final core position to now
            ### note prog_position requires dimensionless init_displacement in kpc, km/s
            new_init_displacement = np.hstack([core_pos, core_vel])
            time_to_integrate = int(i-tdis_estimate)
            prog_w = prog_position(init_displacement=new_init_displacement, i=time_to_integrate)

        if use_core==False: # option 2 is to just use the integrated progenitor orbit from zero. 
            if init_displacement is None:
                raise BaseException("enter an init_displacement if not using core.")
            
            prog_w = prog_position(init_displacement=init_displacement, i=i)


        # transform to jake units
        prog_pos = prog_w[:3] * (u.kpc)
        prog_vel = prog_w[3:] * (u.km/u.s)
        # concatenate. 
        prog_w_jake_units = np.hstack([
            prog_pos.value, prog_vel.to(u.kpc/u.Myr).value
        ])     

    if load_all==True:
        # load all particles, put in the galactocentric frame, get stream coordinates.
        header = petar.PeTarDataHeader(path+'data.'+str(file_i), external_mode='galpy')
        all_particles = petar.Particle(interrupt_mode=interrupt, external_mode='galpy')

        all_particles.loadtxt(file, skiprows=1)
        CM_pos = (header.pos_offset*u.pc).to(u.kpc)
        CM_vel = (header.vel_offset*(u.pc/u.Myr)).to(u.kpc/u.Myr)
        CM_w = np.hstack([CM_pos.value, CM_vel.value])


        all_pos = (all_particles.pos*u.pc).to(u.kpc) + CM_pos
        all_vel = (all_particles.vel*(u.pc/u.Myr)).to(u.kpc/u.Myr) + CM_vel
        all_w = np.hstack([all_pos.value, all_vel.value])


        stream_obj = StreamFrame(sim_coords = all_w, prog_sim_coord = prog_w_jake_units)#CM_w)
        coords = stream_obj.GetStreamFrame()

    # load binaries
    if load_binaries==True:
        binary_file = path+"data."+str(file_i)+".binary"
        binaries = petar.Binary(member_particle_type=petar.Particle,
                                G=petar.G_MSUN_PC_MYR, interrupt_mode=interrupt,
                                external_mode="galpy")

        binaries.loadtxt(binary_file)#, skiprows=1)

    if load_singles==True:
        # load singles
        single_file = path+"data."+str(file_i)+".single"
        singles = petar.Particle(interrupt_mode=interrupt,
                                        external_mode='galpy')

        singles.loadtxt(single_file)#, skiprows=1)

    #### THIS PART IS JUST TO PUT THE SINGLE/BINARY DATA IN THE GALACTOCENTRIC FRAME, NOT FOR THE PROGENITOR COORDINATE!
    core_data = petar.Core(interrupt_mode=interrupt, external_mode='galpy')
    
    core_data.loadtxt(path+'data.core')
    core_pos = (core_data.pos[file_i]*u.pc).to(u.kpc)
    core_vel = (core_data.vel[file_i]*(u.pc/u.Myr)).to(u.kpc/u.Myr) # **not corrected !
    core_w = np.hstack([core_pos.value, core_vel.value])

    if load_singles==True:
        # put singles in the galactocentric frame
        single_pos = (singles.pos*u.pc).to(u.kpc) + core_pos
        single_vel = (singles.vel*(u.pc/u.Myr)).to(u.kpc/u.Myr) + core_vel
        single_w = np.hstack([single_pos.value, single_vel.value])
        single_stream_obj = StreamFrame(sim_coords = single_w, prog_sim_coord = prog_w_jake_units)#core_w)
        single_coords = single_stream_obj.GetStreamFrame()


    if load_binaries==True:
        # put binaries in the galactocentric frame
        binary_pos = (binaries.pos*u.pc).to(u.kpc) + core_pos
        binary_vel = (binaries.vel*(u.pc/u.Myr)).to(u.kpc/u.Myr) + core_vel
        binary_w = np.hstack([binary_pos.value, binary_vel.value])
        binary_stream_obj = StreamFrame(sim_coords = binary_w, prog_sim_coord = prog_w_jake_units)#core_w)
        binary_coords = binary_stream_obj.GetStreamFrame()

    
    particle_data = []
    streamframe_data = []

    if load_all==True:
        particle_data.append(all_particles)
        streamframe_data.append(coords)

    if load_singles==True:
        particle_data.append(singles)
        streamframe_data.append(single_coords)

    if load_binaries==True:
        particle_data.append(binaries)
        streamframe_data.append(binary_coords)

    return particle_data, streamframe_data

def CM_to_galcen_frame(path, particles, i):
    header = petar.PeTarDataHeader(path+"data."+str(i), external_mode='galpy')
    CM_pos = header.pos_offset*u.pc
    CM_vel = (header.vel_offset*(u.pc/u.Myr)).to(u.km/u.s)
    # add center of mass position / move to galctocentric frame
    all_pos = (particles.pos*u.pc) + CM_pos
    all_vel = (particles.vel*(u.pc/u.Myr)).to(u.km/u.s) + CM_vel
    
    return all_pos.to(u.pc), all_vel.to(u.km/u.s)

def core_to_galcen_frame(path, particles, i, core=None, interrupt="bse"):
    """
    note, here 'i' should be a FILE INDEX (for indexing the core position)
    """
    pos = particles.pos*u.pc
    vel = (particles.vel*(u.pc/u.Myr)).to(u.km/u.s)
    
    if core is None:
        core = petar.Core(interrupt_mode=interrupt, external="galpy")
        core.loadtxt(path+"data.core")

    core_pos = core.pos[i] * u.pc
    core_vel = (core.vel[i] * (u.pc/u.Myr)).to(u.km/u.s)
    
    pos+=core_pos
    vel+=core_vel
    return pos.to(u.pc), vel.to(u.km/u.s)

def xform_to_core_frame(path, particles, i, interrupt="bse", file_naming_convention="every integer"):
    """
    pass a petar.Particles object and the corresponding i sim timestep
    returns w (phase space position in core frame)
    *** i is the desired simulation time not the file index ***
    """
    if file_naming_convention=="every integer":
        header = petar.PeTarDataHeader(path+"data."+str(i), external_mode='galpy')
        index = i
    if file_naming_convention=="every 10":
        header = petar.PeTarDataHeader(path+"data."+str(int(i/10)), external_mode='galpy')
        index = int(i/10)
    

    CM_pos = header.pos_offset*u.pc
    CM_vel = (header.vel_offset*(u.pc/u.Myr)).to(u.km/u.s)
    # add center of mass position / move to galctocentric frame
    all_pos = (particles.pos*u.pc) + CM_pos
    all_vel = (particles.vel*(u.pc/u.Myr)).to(u.km/u.s) + CM_vel

    # subtract core position / move to core frame
    core = petar.Core(interrupt_mode=interrupt, external="galpy")
    core.loadtxt(path+"data.core")
    
    core_pos = core.pos[index] *u.pc
    core_vel = (core.vel[index] * (u.pc/u.Myr)).to(u.km/u.s)

    pos_rel = all_pos - core_pos
    vel_rel = all_vel - core_vel
    
    xrel, yrel, zrel = pos_rel.T
    rrel = np.sqrt(xrel**2 + yrel**2 + zrel**2)
    
    return pos_rel.to(u.pc), vel_rel.to(u.km/u.s), rrel.to(u.pc)

def clip_outside_rtid(path, particles, i, interrupt="bse", in_core_frame=True,
                      file_naming_convention="every integer"):
    if not in_core_frame:
        pos_rel, vel_rel, rrel = xform_to_core_frame(path, particles, i, interrupt,
                                                    file_naming_convention)
        
    if in_core_frame:
        pos_rel, vel_rel = particles.pos*u.pc, particles.vel*(u.km/u.s)
        x, y, z = pos_rel.T
        rrel = np.sqrt(x**2 + y**2 + z**2)
        
    tidal = load_tidal(path)

    if file_naming_convention=="every integer":
        index=i
    if file_naming_convention=="every 10":
        index = int(i/10)

    rtid = tidal.rtid[index] * u.pc
    
    clip = rrel<=rtid
    return rrel, clip
    

def compute_cluster_structure(path, i_list, init_displacement, interrupt="bse", save=False, savepath=None, density_shell_width=0.15):
    """
    i_list, init_displacement should be np arrays
    path should be a string.
    return an array of half mass radii over i_list
    array of nbounds over i_list
    dissolution time (last timestep at which nbound >100 stars
    """
    hmrs = []
    nbounds = []
    mass_bounds = []
    t_rhs = []
    t_dyns = []
    
    tidal = petar.external.Tidal()
    tidal.loadtxt(path+"data.tidal")
    rtid = tidal.rtid * u.pc
    for j in tqdm(range(len(i_list))):
        i = i_list[j]
        file = path+"data."+str(i)
        # if bse==True:
        all_particles = petar.Particle(interrupt_mode=interrupt, external_mode='galpy')
        all_particles.loadtxt(file, skiprows=1)
        
        
        pos_rel, vel_rel, rrel = xform_to_core_frame(path, all_particles, i, interrupt=interrupt)
        in_rtid = rrel.to(u.pc) <= rtid[i]
        
        nbound = len(rrel[in_rtid])
        nbounds.append(nbound)
        
        mass_bound = np.sum(all_particles.mass[in_rtid] * u.Msun)
        mass_bounds.append(mass_bound.to(u.Msun).value)
        
        if nbound<=100:
            hmrs.append(0.)
            t_rhs.append(0.)
            
        else:
            hmr = calculate_half_mass_radius(all_particles.mass[in_rtid]*u.Msun, rrel[in_rtid].to(u.pc)) * u.pc
            hmrs.append(hmr.to(u.pc).value)
                        
            shell_width = density_shell_width*u.pc
            inner = hmr-shell_width
            outer = hmr+shell_width
            in_shell = (rrel>inner) & (rrel<outer)
            
            shell_volume = (4*np.pi/3) * (outer**3 - inner**3)
            shell_mass = np.sum(all_particles.mass[in_shell]) * u.Msun
            shell_density = shell_mass / shell_volume
            
            # print(rho_avg.decompose().unit)
            
            t_cross = (const.G * shell_density)**(-1/2)
            t_dyns.append(t_cross.to(u.Myr).value)
            # print(t_cross.decompose().unit)
            t_rh = ((0.1*nbound)/(np.log(nbound))) * t_cross
            t_rhs.append(t_rh.to(u.Myr).value)
       
    hmrs = np.array(hmrs)
    nbounds = np.array(nbounds)
    mass_bounds = np.array(mass_bounds) # in msun
    t_rhs = np.array(t_rhs)
    t_dyns = np.array(t_dyns)
    # indices at which nbounds>=100:
    bound_indices = i_list[nbounds>=100]
    t_dis = np.array([max(bound_indices)])
    
    if save==True:
        np.savez(savepath,
                 i_list = i_list,
                 hmrs = hmrs,
                 nbounds = nbounds,
                 mass_bounds = mass_bounds,
                 t_rhs = t_rhs,
                 t_dis = t_dis,
                 allow_pickle=True)
    
    return hmrs, nbounds, mass_bounds, t_rhs, t_dyns, t_dis

def calc_dispersion(x):
    x2 = x**2
    meanx = np.mean(x)
    meanx2 = np.mean(x2)
    sig2 = meanx2 - (meanx**2)
    return np.sqrt(sig2)

def calc_dispersion_with_3sig_clip(x):
    x2 = x**2
    meanx = np.mean(x)
    meanx2 = np.mean(x2)
    sig2 = meanx2 - (meanx**2)
    sig = np.sqrt(sig2)
    
    clip = np.abs(x-meanx)<=3*sig
    x_new = x[clip]
    x2_new = x_new**2
    meanx_new = np.mean(x_new)
    meanx2_new = np.mean(x2_new)
    sig2_new = meanx2_new - (meanx_new**2)
    return np.sqrt(sig2_new)


def get_med_trim_outliers(data):
    l, h = np.percentile(data, [5,95])
    data_clipped = data[(data>l) & (data<h)]
    return np.median()

def straighten_stream_binmeds(phi1, y, trim_criteria, 
                              bins=None, sigma_kernel=3):
    inMW, trim = trim_criteria
    phi1_trimmed = phi1[inMW][trim]
    y_trimmed = y[inMW][trim]
    ### get the fit: 
    
    if bins is None:
        nbins=200
        bins = np.linspace(min(phi1_trimmed), max(phi1_trimmed), nbins+1)
    bin_centers = 0.5*(bins[:-1]+bins[1:])
    
    med, _, _ = binned_statistic(x=phi1_trimmed, values=y_trimmed,
                                  statistic='median', bins=bins)

    good = np.isfinite(med)
    # if np.sum(good) < 2:
    #     raise ValueError("Not enough populated bins to build baseline.")

    med_filled = np.interp(bin_centers, bin_centers[good], med[good])

    # now smooth
    med_smooth = gaussian_filter1d(med_filled, sigma=sigma_kernel)
    
    # med_smooth = gaussian_filter1d(med, sigma_kernel)
    baseline = np.interp(phi1, bin_centers, med_smooth)
    y_smooth = y - baseline

    return phi1, y_smooth



def straighten_stream_polynomial(phi1,y, degree=5, show_plot=False, return_poly_fn=False,
                                trim_criteria=None):
    """
    straighten a streamframe object's phi1/phi2 coordinates 
    by fitting a high-order polynomial
    trim criteria optional, how to trim the stream before the polyfit to avoid sensitivity to outliers. 
        * should be a list, [inMW, trim]
    """
    inMW, trim = trim_criteria
    def make_polynomial(order):
        # Create the argument list: a0, a1, ..., an
        arg_list = ", ".join([f"a{i}" for i in range(order + 1)])

        # Build the function definition string
        func_str = f"def poly(x, {arg_list}):\n"
        func_str += "    return " + " + ".join([f"a{i}*x**{i}" for i in range(order + 1)]) + "\n"

        # Local namespace for exec
        local_ns = {}
        exec(func_str, {}, local_ns)
        return local_ns['poly']
    
    poly=make_polynomial(order=degree)

    # next fit a polynomial and subtract to straighten out the stream using only the trimmed data. 
    fit, cov = curve_fit(f=poly, xdata=phi1[inMW][trim], ydata=y[inMW][trim])
    new_y = y - poly(phi1, *fit)

    if show_plot==True:
        fig, [ax1,ax2] = plt.subplots(2,1,figsize=[10,20])
        x = np.linspace(min(phi1), max(phi1))
        y = poly(x, *fit)
        ax1.scatter(phi1, y, s=.1)
        ax1.plot(x, y) 
                                    
        ax2.scatter(phi1, new_y, s=.1)
        ax2.set_aspect('equal')

    if return_poly_fn==False:
        return phi1, new_y
    if return_poly_fn==True:
        return phi1, new_y, poly, fit


def straighten_stream_orbit_interp(coords, yval, core, i, 
                                   trim_criteria=None,
                                   Dt_start=375, # Myr
                                   return_orbit_chunk=False, 
                                   init_displacement=None,
                                   use_core=True,
                                   correct_core_vel=True,
                                   verbose=False,
                                   file_index=None):
    """
    coords: a dictionary from streamframe script
    yval: a string indexing the y coordinate of the stream coord (x assumed phi1)
          OR a list of strings, e.g., ['r', 'vr'] in which case the all straightened coords in the list
          will be returned. 
    core: a petar.Core() object
    i: a time at which the straightening occurs (to get the core position) <----should be a file index if using core, a time if using the integrated prog orbit!!!
    Dt: a number of Myr to integrate forward/backward to get the prog orbit from time i
    """
    if file_index is None:
        file_i=i
    else:
        file_i=file_index

    if trim_criteria is None:
        phi1_min_data = min(coords['phi1'])
        phi1_max_data = max(coords['phi1'])

    else:
        inMW, trim = trim_criteria # trim_criteria should be a tuple or list.

        # get range in phi1 of data (to ensure the interpolant covers all of it)
        phi1_min_data = min(coords['phi1'][inMW][trim])
        phi1_max_data = max(coords['phi1'][inMW][trim])

    # get present-day core position and velocity to set up the integration. 

    if use_core==True:
        if core is None:
            raise BaseException("pass a core object as core=[core]")
        core_pos = core.pos[file_i] * u.pc
        if correct_core_vel==True:
            corrected_core_vel = fix_core_vel(core)
        if correct_core_vel==False:
            corrected_core_vel = core.vel
        
        core_vel = corrected_core_vel[file_i] * u.pc/u.Myr
    
    if use_core==False:
        if init_displacement is None:
            raise BaseException("pass a init_displacement if not using core.")
        
        prog_w = prog_position(init_displacement=init_displacement, i=i) # <-- this is a time!
        core_pos = prog_w[:3] * (u.kpc)
        core_vel = prog_w[3:] * (u.km/u.s)


    core_w0_sf = np.hstack([core_pos.to(u.kpc).value, core_vel.to(u.kpc/u.Myr).value]) # prog position for streamframe purposes
    # do the gala orbit:
    core_w0 = gd.PhaseSpacePosition(core_pos, core_vel) # prog position for orbit integration forward/backward purposes. 

    
    mwp = gp.BovyMWPotential2014(units=galactic)
    H = gp.Hamiltonian(mwp)

    Dt = Dt_start
    Dt_step = 50
    last_Dt_step=Dt_step
    last_case=None

    max_iters = 100 # return a failure if this takes >100 iterations... 
    ii = 0
    while ii<max_iters: # ensure that there are no large jumps where the orbit circles around in phi1
        orbit_forward = H.integrate_orbit(core_w0, dt=1, n_steps = Dt)
        orbit_backward = H.integrate_orbit(core_w0, dt=-1, n_steps = Dt)

        # concatenate orbit forward/backward info into something that StreamFrame can use...
        orbit_pos_f = np.array([
            orbit_forward.pos.x.to(u.kpc).value,
            orbit_forward.pos.y.to(u.kpc).value,
                orbit_forward.pos.z.to(u.kpc).value
        ]).T
        orbit_pos_b = np.array([
            orbit_backward.pos.x.to(u.kpc).value,
            orbit_backward.pos.y.to(u.kpc).value,
                orbit_backward.pos.z.to(u.kpc).value
        ]).T[::-1]
        orbit_pos = np.vstack([orbit_pos_b, orbit_pos_f])

        orbit_vel_f = np.array([
            orbit_forward.vel.d_x.to(u.kpc/u.Myr).value,
            orbit_forward.vel.d_y.to(u.kpc/u.Myr).value,
                orbit_forward.vel.d_z.to(u.kpc/u.Myr).value
        ]).T
        orbit_vel_b = np.array([
            orbit_backward.vel.d_x.to(u.kpc/u.Myr).value,
            orbit_backward.vel.d_y.to(u.kpc/u.Myr).value,
                orbit_backward.vel.d_z.to(u.kpc/u.Myr).value
        ]).T[::-1]
        orbit_vel = np.vstack([orbit_vel_b, orbit_vel_f])

        orbit_w = np.hstack([orbit_pos, orbit_vel])
        orbit_streamobj = StreamFrame(sim_coords=orbit_w, prog_sim_coord=core_w0_sf)
        orbit_coords = orbit_streamobj.GetStreamFrame()   

        # ensure that the range in orbit coords captures that of the data. 
        max_phi1_orbit = max(orbit_coords['phi1'])
        min_phi1_orbit = min(orbit_coords['phi1'])
        orbit_range_danger_zone = np.max(np.abs(orbit_coords['phi1']))
        
        dphi1_max_orbit = np.max(np.abs(np.diff(orbit_coords['phi1'])))

        #### CASE BOOLS:
        covered = (max_phi1_orbit >= phi1_max_data) and (min_phi1_orbit <= phi1_min_data)
        wrap_like = (dphi1_max_orbit > 100)   # or whatever threshold makes sense after unwrapping      
        
        if covered and (not wrap_like): # perfect ! amazing !
            if verbose:
                print("OK")

            case="PERFECT. RIGOROUS, EVEN."
            break


        if wrap_like: ## avoid wrap issues first and foremost!!! START TAKING THE TIMESTEP DOWN
            case="wrap_issue"
            Dt=max(1, Dt-Dt_step)

        else: # if not a wrap issue, try increasing the coverage
            case="need_more_coverage"
            Dt+=Dt_step


        # halve step only if we flipped case
        if (last_case is not None) and (case != last_case):
            last_Dt_step = Dt_step
            Dt_step = max(1, Dt_step // 2)       

        if verbose:
            print(f"{case}: Dt={Dt} step={Dt_step} covered={covered} wrap_like={wrap_like} dphi1_max={dphi1_max_orbit:.2f}")

        # stop refinement if step is tiny but we still can't satisfy both
        if Dt_step == 1 and last_Dt_step == 1 and wrap_like: ### OKAY. IF WE ARE PING-PONGING AND STILL WRAP LIKE, CUT THINGS OFF!!!
            # best we can do near boundary; accept this Dt but warn
            orbit_coords = last_orbit_coords
            if verbose:
                print("Warning: step==1 and still wrap-like; returning best attempt (before wrap started).")
            break

        last_case = case
        last_orbit_coords = orbit_coords
        ii += 1



    if type(yval)==str: # when I request only one string, only return that to me.
        def interp_orbit(phi1):
            return np.interp(phi1, orbit_coords['phi1'], orbit_coords[yval]) 
        y_new = coords[yval] - interp_orbit(coords['phi1'])

    else:
        interp_orbit = []
        y_new = []
        for y in yval:
                
            def interp_orbit_fn(phi1):
                return np.interp(phi1, orbit_coords['phi1'], orbit_coords[y])
            interp_orbit.append(interp_orbit_fn)
            y_new_now = coords[y]-interp_orbit_fn(coords['phi1']) 
            y_new.append(y_new_now)

    if return_orbit_chunk==True:
        return y_new, interp_orbit, orbit_coords, orbit_w, ii
    
    else:
        return y_new, interp_orbit, ii

def trim_coords_percentile(coords, low, high, apo):
    """
    assumes apo is in kpc
    """
    inMW = coords['r'] <= 1.5*apo#.to(u.kpc).value # first remove high-velocity stars...
    
    trim_keys = ['phi1', 'phi2']#, 'r']

    # NEXT clip in-MW stars. 
    criteria = []
    for key in trim_keys:
        key_low, key_high = np.percentile(coords[key][inMW], q=[low, high])
        key_crit = (coords[key][inMW]<=key_high) & (coords[key][inMW]>=key_low)
        criteria.append(key_crit)
        # print(key, key_low, key_high)

    trim_criteria = criteria[0] & criteria[1] #& criteria [2]

    return inMW, trim_criteria

# concatenate single and binary coordinates. 
def concat_sb_coords(single_coords, binary_coords):
    keys = ['phi1', 'phi2', 'pm_phi1','pm_phi2','r', 'vr']
    combined = {
        key:np.concatenate([single_coords[key], binary_coords[key]]) for key in keys
    }
    return combined



def get_ICRS_coords(path, i, interrupt="bse"):
    """
    return ICRS coordinates object
    provide path to PeTar data.# files and i
    """
    # load coordinates
    file = path+'data.'+str(i)
    header = petar.PeTarDataHeader(path+'data.'+str(i), external_mode='galpy')
    all_particles = petar.Particle(interrupt_mode=interrupt, external_mode='galpy')
    all_particles.loadtxt(file, skiprows=1)
    pos = all_particles.pos * u.pc
    vel = all_particles.vel * (u.pc/u.Myr)
    CM_pos = header.pos_offset*u.pc
    CM_vel = header.vel_offset * (u.pc/u.Myr)
 
    # transform out of CM frame
    pos+=CM_pos
    vel+=CM_vel

    # create a cartesian representation/differential
    rep = CartesianRepresentation(pos.T)
    rep_vel = CartesianDifferential(vel.T)
    rep = rep.with_differentials(rep_vel)

    # create coords in galactocentric frame
    galcen_frame = Galactocentric()
    coords_galcen = SkyCoord(rep, frame=galcen_frame)

    # transform to ICRS
    coords_ICRS = coords_galcen.transform_to(ICRS())
    return coords_ICRS


def get_streamcoords_from_ICRS(ICRS_coords, try_every=1):
    """
    for when I want to optimize. 
    get phi1, phi2 from transforming to ICRS coordinates, fitting a great circle coordinate frame
    then fitting a quadratic, cubic, or spline and subtracting it. 
    for finding stream widths; progenitor will not necessarily be centered.

    returns gc_frame_best, xformed_coords
    """
    obfun_best = np.inf
    gc_frame_best = None
    point1_best = None
    point2_best = None

    point1 = SkyCoord(
        ra = np.nanmedian(ICRS_coords.ra),
        dec = np.nanmedian(ICRS_coords.dec),
        frame='icrs'
    )
    
    print("iterating to find best frame to minimize phi2")
    for i in tqdm(range(0, len(ICRS_coords), try_every)):
        point2 = ICRS_coords[i]

        try:
            gc_frame = gc.GreatCircleICRSFrame.from_endpoints(point1, point2)
            stars_sc_gc = ICRS_coords.transform_to(gc_frame)
            obfun = np.sum(stars_sc_gc.phi2.value**2)

            if obfun < obfun_best:
                obfun_best = obfun # update objective function
                gc_frame_best = gc_frame
                point2_best = point2

        except Exception as e:
            continue # skipped failed point2s
    
    xformed_coords = ICRS_coords.transform_to(gc_frame_best)
    return gc_frame_best, xformed_coords



def calculate_half_mass_radius(ms, rs):
    """
    this is for checking the half mass radius
    for sanity purposes
    units of ms don't matter, will return r_h in whatever units "rs" is in
    """
    radii = rs
    masses = ms

    # Sort stars by radius
    sorted_indices = np.argsort(radii)
    sorted_radii = np.array(radii)[sorted_indices]
    sorted_masses = np.array(masses)[sorted_indices]

    # Compute cumulative mass
    cumulative_mass = np.cumsum(sorted_masses)

    # Total mass
    total_mass = np.sum(masses)

    # Find the half-mass radius
    half_mass = total_mass / 2
    half_mass_radius_index = np.searchsorted(cumulative_mass, half_mass)
    half_mass_radius = sorted_radii[half_mass_radius_index]
    # print("half mass radius = %.3f pc"%half_mass_radius)
    return half_mass_radius 

################ STATISTICS

def find_minima(arr):
    min_indeces = []
    min_values = []
    for i,a in enumerate(arr):
        # print(i)
        if i==0 or i==int(len(arr)-1):
            # print("first/last value, skipping")
            continue
        if (arr[i-1]>a) & (arr[i+1]>a):
            # print("appending a local minimum")
            min_indeces.append(i)
            min_values.append(a)

    return np.array(min_indeces), np.array(min_values)

def find_maxima(arr):
    max_indeces = []
    max_values = []
    for i, a in enumerate(arr):
        if i==0 or i==int(len(arr)-1):
            continue
        if (arr[i-1]<a) & (arr[i+1]<a):
            max_indeces.append(i)
            max_values.append(a)

    return np.array(max_indeces), np.array(max_values)


## for uncertainties in the binary fraction. 
def Prob_of_frac(k, N, parr=np.linspace(0, 1, 1000)): # uniform prior??
    """
    return the probability mass function for p given k successes in N trials
    """
    return parr, np.array([binom.pmf(k, N, p) for p in parr]) # probability mass function

def percentile(p, Prob, percentiles=[16,50,84]):
    """
    return percentile values of the binomial dist???
    """
    cdf = np.cumsum(Prob)
    cdf /= cdf.max()
    cdf *= 100 
    values = np.interp(percentiles, cdf, p)
    return values

def calc_dispersion_percentile(v, l=5, h=95):
    pl = np.percentile(v, l)
    ph = np.percentile(v, h)
    return ph-pl

def dispersion_5_95(data):
    low, high = np.percentile(data, q=[5,95])
    return high-low

def dispersion_1_99(data):
    low, high = np.percentile(data, q=[1,99])
    return high-low

def dispersion_16_84(data):
    low, high = np.percentile(data, q=[16,84])
    return high-low

def p16(data):
    return np.percentile(data, 16)
def p84(data):
    return np.percentile(data, 84)
def p5(dat):
    return np.percentile(dat, 5)
def p95(dat):
    return np.percentile(dat, 95)
#--------------------------------------------------------#
#.     Mock observations and detection fractions.        #
#--------------------------------------------------------#

def draw_inclinations(n, rng=None):
    """
    draw n isotropic inclinations
    """
    if rng is None:
        rng = np.random.default_rng()
        
    theta = np.arccos(1-2*rng.random(n))#np.random.rand(n))
    return theta

def get_orbital_params(paths, times, n, rng=None):
    """
    retrieve orbital parameters from path paths[n] at time times[n]
    returns an array of params
    [v0 (km/s), K (km/s), w, phi0, e, P (day)]
    where w, phi1 are uniformly sampled and an isotropic inclination is picked to compute k
    """
    i = times[n]
    path = paths[n]

    core = petar.Core(interrupt_mode='bse', external_mode='galpy')
    core.loadtxt(path+"data.core")
    core_pos = core.pos[i] * u.pc.to(u.kpc) # dimensionless core position in kpc
    core_vel = core.vel[i] * (u.pc/u.Myr).to(u.kpc/u.Myr) # dimensionless core velocity in kpc/myr
    core_w_jake_units = np.hstack([core_pos, core_vel])

    binaries = petar.Binary(member_particle_type=petar.Particle, G=petar.G_MSUN_PC_MYR,
                            interrupt_mode='bse', external_mode='galpy')
    binaries.loadtxt(path+"data.%i.binary"%i)#, skiprows=1)
    binary_pos = binaries.pos*u.pc.to(u.kpc)+core_pos
    binary_vel = binaries.vel*(u.pc/u.Myr).to(u.kpc/u.Myr)+core_vel
    binary_w = np.hstack([binary_pos, binary_vel])



    binary_stream_obj = StreamFrame(sim_coords=binary_w, prog_sim_coord=core_w_jake_units)
    binary_coords = binary_stream_obj.GetStreamFrame()

    ###### collect everything we need
    a_vals = binaries.semi*u.pc
    Mtot_vals = binaries.mass*u.Msun
    P_vals = calc_P(a_vals, Mtot_vals)

    if rng is None:
        rng = np.random.default_rng()

    inclinations = draw_inclinations(len(a_vals), rng)

    K_vals = np.array([calc_amplitude(binary, i) for binary, i in zip(binaries, inclinations)]) * u.m/u.s

    e_vals = binaries.ecc

    phi1_vals = binary_coords['phi1'] # degrees
    v0_vals = (binary_coords['vr']*u.km/u.s).to(u.m/u.s) # extract systemic velocities.



    ### draw arguments of periapsis and mean anomaly phase offsets ?? 

    w_vals = rng.uniform(low=0, high=2*np.pi, size=len(a_vals))
    phi0_vals = rng.uniform(low=0, high=1, size=len(a_vals))
    
    params_all = np.array([v0_vals.to(u.km/u.s).value, 
                           K_vals.to(u.km/u.s).value,
                           w_vals,
                           phi0_vals,
                           e_vals,
                           P_vals.to(u.day).value]
                          ).T
    
    return params_all, phi1_vals

def solve_kepler(M, e, tol=1e-10, max_iter=100):
    """
    Vectorized Kepler solver using Newton-Raphson with safety.
    """
    M = np.asarray(M)
    e = np.asarray(e)

    # Ensure shapes are compatible
    if M.shape != e.shape:
        e = np.full_like(M, e)

    E = M.copy()  # initial guess

    for _ in range(max_iter):
        f = E - e * np.sin(E) - M
        f_prime = 1 - e * np.cos(E)
        delta = f / f_prime

        # Protect against divide-by-zero or overflow
        delta = np.where(np.isfinite(delta), delta, 0.0)
        E_new = E - delta

        # Convergence mask
        if np.all(np.abs(delta) < tol):
            break
        E = E_new

    # Final sanity check
    E = np.where(np.isfinite(E), E, np.nan)
    return E

def true_anomaly(E, e):
    """
    Convert eccentric anomaly E to true anomaly nu safely.
    """
    sqrt_1_plus_e = np.sqrt(np.clip(1 + e, 0, None))
    sqrt_1_minus_e = np.sqrt(np.clip(1 - e, 0, None))

    sin_E2 = np.sin(E / 2)
    cos_E2 = np.cos(E / 2)

    # Replace NaNs with 0 to avoid propagating errors
    sin_E2 = np.nan_to_num(sin_E2)
    cos_E2 = np.nan_to_num(cos_E2)

    return 2 * np.arctan2(
        sqrt_1_plus_e * sin_E2,
        sqrt_1_minus_e * cos_E2
    )

def radial_velocity(t, params):
    """
    t : times at which to compute RV
    v0 : systemic velocity (not a quantity, but in km/s)
    K : RV semiamplitude (not a quantity, but in km/s)
    w : arg of periapsis
    e : eccentricity
    phi_0 : mean anomaly phase offset
    P : period (in same units as t)
    """
    v0, K, w, phi_0, e, P = params


    M = 2 * np.pi * t / P - phi_0
    E = solve_kepler(M % (2 * np.pi), e)
    nu = true_anomaly(E, e)
    vr = v0 + K * (np.cos(nu + w) + e * np.cos(w))
    ### in another version i might add gaussian noise with sigma=.1 km/s to this. 
    ### returns radial velocity in whatever units vr and v0 are in!
    return vr

def get_obstimes(N_obsm, N, rng=None):
    dt_min = 30
    dt_max = 3*360

    if rng is None:
        rng = np.random.default_rng()

    base = np.repeat(0, N)
    gap1 = rng.uniform(30,90, size=N)
    gap2 = rng.uniform(3*365, 5*365, size=N)

    deltaTs = np.vstack((base, gap1, gap2)).T

    obstimes_all = np.cumsum(deltaTs, axis=1) ##### THIS IS WHAT WILL GO INTO THE RV GENERATION FUNCTION!   
    return obstimes_all

def get_rvs(params_all, obstimes_all, verbose=True,
            add_noise=False, noise_level=None, rng=None):
    """
    add gaussian noise option; defaults to false
    noise level in km/s
    """

    RVs_all = []
    N=len(params_all[:,0])

    iterator = tqdm(range(N)) if verbose else range(N)
    for j in iterator:
        params = params_all[j]
        obstimes = obstimes_all[j]

        rvs = radial_velocity(obstimes, params)
        if add_noise==True:
            rvs += rng.normal(0, noise_level, size=obstimes.shape)

        RVs_all.append(rvs)


    rvs_all = np.array(RVs_all)
    return rvs_all


def get_detections(e_rv, rvs_all, v0_vals, bool_arr="undet"): #return "undet" of "det"
    """
    returns a bool array; v0_vals should be dimensionless and in km/s
    """
    mu_rvs = np.mean(rvs_all, axis=1) # vsys
    delta_vsys = np.abs(mu_rvs-v0_vals.to(u.km/u.s).value)
    resid_rvs = rvs_all - mu_rvs[:, None]

    chi2_rvs = np.sum((resid_rvs/e_rv)**2, axis=1)
    Nobs=rvs_all.shape[1] ### previously this was always set to 3 -- bug ! 
    P_chi2 = stats.chi2.sf(chi2_rvs, df=Nobs-1)
    zscore = np.max(np.abs(resid_rvs/e_rv), axis = 1) # idk what this is,

    undet = P_chi2>0.1 # detect binaires when the P value of the chi square test is <0.1 
    
    if bool_arr=='undet':
        return undet, delta_vsys
    if bool_arr=='detet':
        return ~undet, delta_vsys
    


def gen_kroupa_IMF(m_max, N):
    m0, m1, m2 = (0.08, 0.5, m_max) #* u.Msun
    if m_max<0.5:
        print("maximum mass <0.5 Msun not supported sry")
        return 
    
    # define normalization coefficients
    X1 = m0**(-0.3) - m1**(-0.3)
    X2 = m1**(-1.3) - m2**(-1.3)

    A1 = 1/((X1/0.3) + m1*(X2/1.3))
    A2 = m1/((X1/0.3) + m1*(X2/1.3))

    def C1(m):
        return A1 * (m0**(-0.3) - m**(-0.3))/0.3
    # print(C1(m1))
    def C2(m): # don't need actually
        return (A1 * (m0**(-0.3) - m1**(-0.3))/0.3) + (A2 * (m1**(-1.3) - m**(-1.3))/1.3)
    # print(C1(m1)==C2(m1), "should be equal")

    masses = []
    for i in range(N):
        u_rand = np.random.rand()
        if u_rand < C1(m1):
            m = (m0**(-0.3) - (0.3/A1)*u_rand)**(-1/0.3)
            masses.append(m)
        if u_rand >= C1(m1):
            m = (m1**(-1.3) - (1.3/A2)*(u_rand - (A1*X1)/0.3))**(-1/1.3)
            masses.append(m)
        
    return masses



#------------------------------------------#
#    stuff for gala particle spray streams #
#------------------------------------------#
def gen_stream(time, init_displacement, Mprog, release_every=5, b=0.75 * u.pc, 
               save=False, output_every=None,
               output_filename=None,
               streamtype='chen' # or 'streakline'
               ):
    
    pos0 = init_displacement[:3]*u.kpc
    vel0 = init_displacement[3:]*(u.km/u.s)

    prog_w0 = gd.PhaseSpacePosition(pos0, vel0)
    if streamtype=='chen':
        print("running a chen-type particle spray stream")
        df = ms.ChenStreamDF(lead=True, trail=True) # or fardal or something
        prog_mass = Mprog
        prog_pot = gp.PlummerPotential(m=prog_mass,
                                       b=b, units=galactic)


    if streamtype=='streakline':
        print("running a streakline (0-dispersion) stream")
        df = ms.StreaklineStreamDF(lead=True, trail=True)
        prog_mass = Mprog
        prog_pot=None

    

    mwp = gp.BovyMWPotential2014(units=galactic)
    H = gp.Hamiltonian(mwp)

    gen = ms.MockStreamGenerator(df, H, progenitor_potential=prog_pot)
    if save==False:
        stream, prog = gen.run(prog_w0, prog_mass, dt=1*u.Myr, n_steps=int(time),
                                release_every=release_every,
                                output_every=output_every,
                                progress=True)
    if save==True:
        stream, prog = gen.run(prog_w0, prog_mass, dt=1*u.Myr, n_steps = int(time),
                               release_every=release_every, 
                               output_every=output_every,
                               output_filename=output_filename, overwrite=True,
                               progress=True)

    return stream, prog


def get_streamcoords_ms_streamfile(streamfile, i, init_displacement, output_every=5):
    """
    assumes that i is a TIME in Myr
    """
    
    prog_w = prog_position(init_displacement, i=i)
    prog_pos = prog_w[:3] * (u.kpc)
    prog_vel = prog_w[3:] * (u.km/u.s)
    # concatenate. 
    prog_w_jake_units = np.hstack([
        prog_pos.value, prog_vel.to(u.kpc/u.Myr).value
    ])  



    index = int(i/output_every)
    x, y, z = streamfile['stream']['pos'][:,index] # kpc
    vx, vy, vz = streamfile['stream']['vel'][:,index] # kpc/Myr ? 

    all_pos = np.array([
        x, y, z
    ]).T # should be saved in kpc; i.e., no unit gymnastics necessary.
    all_vel = np.array([
        vx, vy, vz
    ]).T # saved be returned in kpc/myr; i.e., no unit gymnastics necessary.

    all_w = np.hstack([all_pos, all_vel])

    stream_obj = StreamFrame(sim_coords = all_w, prog_sim_coord = prog_w_jake_units)
    coords = stream_obj.GetStreamFrame()

    return coords


def get_streamcoords_ms(stream, i, init_displacement):
    """
    stream coordinates for mock streams at the final time from a stream object from gala. 
    """
    prog_w = prog_position(init_displacement, i=i)
    prog_pos = prog_w[:3] * (u.kpc)
    prog_vel = prog_w[3:] * (u.km/u.s)
    # concatenate. 
    prog_w_jake_units = np.hstack([
        prog_pos.value, prog_vel.to(u.kpc/u.Myr).value
    ])  

    all_pos = np.array([
        stream.pos.x.to(u.kpc).value, stream.pos.y.to(u.kpc).value, stream.pos.z.to(u.kpc).value
    ]).T

    all_vel = np.array([
        stream.vel.d_x.to(u.kpc/u.Myr).value, stream.vel.d_y.to(u.kpc/u.Myr).value, stream.vel.d_z.to(u.kpc/u.Myr).value
    ]).T

    all_w = np.hstack([all_pos, all_vel])

    stream_obj = StreamFrame(sim_coords = all_w, prog_sim_coord = prog_w_jake_units)
    coords = stream_obj.GetStreamFrame()

    return coords


#-----------------------------------------------------------------------------------------#
#    stuff for final post processing -- getting everything together by combining stuff    #
#-----------------------------------------------------------------------------------------#
def GET_INTRINSIC_STREAM_DATA(n, i, core, path, apo, use_core=True, init_displacement=None, file_index=None): 
    """
    for simulation index n at time step i load a bunch of stuff about it 
    and concatenate singles + binary p1 + binary p2 data. <-- so this is a reordered order. 
    but where binaries have the center of mass coordinate. 
    NOTE: I return nsingles, nbinaries so that if I just want coordinates and don't want to double count
    the binaries, I can index only up to [:nsingles+nbinaries]
    """
    if file_index is None:
        file_i = i
    else:
        file_i = file_index

    paths = define_paths()
    path = paths[n]
    ### get + organize petar data. as singles + bp1 + bp2

    if use_core==True: # only want to use core if the cluster is like *just* dissolved.... could probably not have split this into cases but whatever. 
        particle_data, streamframe_data = load_coords_v2(path, i, core, tdis_estimate=int(i-1), file_index=file_i,
                                                        tdis_estimate_index=int(file_i-1))
    if use_core==False:
        particle_data, streamframe_data = load_coords_v2(path, i, core=None, 
                                                         use_core=False, check_dissolved=False,
                                                         init_displacement=init_displacement, file_index=file_i)
    all_particles, singles, binaries = particle_data
    all_coords, single_coords, binary_coords = streamframe_data
    bp1_coords, bp2_coords = binary_coords, binary_coords ## give bp1 and bp2 both the binary coords

    # positions and velocities in galactocentric frame -- doing the separate single/binary treatment mostly so that the binary IDs get the cm phase space position. 
    spos, svel = core_to_galcen_frame(path, singles, file_i)
    bpos, bvel = core_to_galcen_frame(path, binaries, file_i)
    bp1pos, bp1vel = bpos, bvel
    bp2pos, bp2vel = bpos, bvel

    # external potentials
    s_pot = singles.pot_ext # pc^2/myr^2
    bp1_pot, bp2_pot = binaries.p1.pot_ext, binaries.p2.pot_ext # not sure if this is reasonable. 

    # <- system masses. 
    smass = singles.mass*u.Msun
    bp1mass, bp2mass = binaries.mass*u.Msun, binaries.mass*u.Msun
    
    # Ids
    sid = singles.id
    bp1id = binaries.p1.id
    bp2id = binaries.p2.id

    ### concatenate everything 
    IDs = np.concatenate([sid, bp1id, bp2id])
    # coords = single_coords | bp1_coords | bp2_coords 
    keys = ['phi1', 'phi2', 'pm_phi1','pm_phi2','r', 'vr']
    coords = {
        key:np.concatenate([single_coords[key], bp1_coords[key], bp2_coords[key]]) for key in keys
    }
    phi1=coords['phi1']
    pots = np.concatenate([s_pot, bp1_pot, bp2_pot]) * u.pc**2 / u.Myr**2
    pos = np.concatenate([spos, bp1pos, bp2pos])
    vel = np.concatenate([svel, bp1vel, bp2vel])
    Msys = np.concatenate([smass, bp1mass, bp2mass])

    ### straighten the stream coordinates. 
    inMW, trim = trim_coords_percentile(coords, low=1, high=99, apo=apo)
    sc, interp_orbit, orbit_coords, orbit_w, itr = straighten_stream_orbit_interp(
        coords, ['phi2','r','vr'], core, i, 
        trim_criteria = [inMW, trim], Dt_start=240,
        return_orbit_chunk=True, use_core=use_core, init_displacement=init_displacement, file_index=file_index
    )
    phi2_straight, r_straight, vr_straight = sc 

    nsingles, nbinaries = len(singles.mass), len(binaries.mass)
    return core, IDs, coords, phi1, pots, pos, vel, phi2_straight, r_straight, vr_straight, Msys, inMW, trim, nsingles, nbinaries



#-----------------------------------------------------------------------------------------#
#    stuff for final post processing -- getting everything together by combining stuff    #
#-----------------------------------------------------------------------------------------#
def intrinsic_stream_data_v2(n, i, 
                             core, path, apo, 
                             use_core=True, init_displacement=None, 
                             file_index=None,
                             binary_treatments = ["CoM","companions","luminous"] # <-- "CoM" to do the analysis with center of mass values, "companions" to use the values for the more luminous companion. 
                             ): 
    """
    for simulation index n at time step i load a bunch of stuff about it 
    and concatenate singles + binary p1 + binary p2 data. <-- so this is a reordered order. 

    notes:
        binary_treatment=options are 'CoM', 'companions', 'luminous' <--provide as list

    NOTE: I return nsingles, nbinaries so that if I just want coordinates and don't want to double count
    the binaries, I can index only up to [:nsingles+nbinaries]
    """

    if file_index is None:
        file_i = i
    else:
        file_i = file_index

    paths = define_paths()
    path = paths[n]
    
    data_dict = {} # <-- I will return this. 
    data_dict["sim_n"] = n
    data_dict["init_displacement"] = init_displacement #<-- so i don't have to do this later... 

    #### load particle and streamframe data:
    if use_core==True: # only want to use core if the cluster is like *just* dissolved.... could probably not have split this into cases but whatever. 
        particle_data, streamframe_data = load_coords_v2(path, i, core, tdis_estimate=int(i-1), file_index=file_i,
                                                        tdis_estimate_index=int(file_i-1))
    if use_core==False:
        particle_data, streamframe_data = load_coords_v2(path, i, core=None, 
                                                         use_core=False, check_dissolved=False,
                                                         init_displacement=init_displacement, file_index=file_i)

    all_particles, singles, binaries = particle_data
    allpos, allvel = CM_to_galcen_frame(path, all_particles, file_i)
    nsingles, nbinaries = len(singles.mass), len(binaries.mass)
    ### number of single and binary stars are stored at the top of the data dictionary. 
    data_dict['nsingles'] = nsingles
    data_dict['nbinaries'] = nbinaries

    all_coords, single_coords, binary_coords = streamframe_data
    all_IDs = all_particles.id

    # Ids
    sid = singles.id
    bp1id = binaries.p1.id
    bp2id = binaries.p2.id
    luminous_mask = binaries.p1.star.lum >= binaries.p2.star.lum # <--- use np.where(luminous_mask, p1 property, p2 property) to index the property of the more luminous companion. 
    data_dict['IDs'] = np.concatenate([sid, bp1id, bp2id]) # <-- ids will be in the top level of the dictionary

    # create a lookup table to index binary p1 and p2 information in the all particles table. (rly just needed for the streamframe coordinate data.)
    lookup = {v:i for i, v in enumerate(all_IDs)}
    mask_bp1 = np.array([lookup[x] for x in bp1id])
    mask_bp2 = np.array([lookup[x] for x in bp2id])

    # external potentials
    s_pot = singles.pot_ext # pc^2/myr^2
    #### binary potential values will always just be the two values.... going to assume it's not drastically different between them for actual bound binaries. 
    bp1_pot, bp2_pot = binaries.p1.pot_ext, binaries.p2.pot_ext 
    data_dict['pot'] = np.concatenate([s_pot, bp1_pot, bp2_pot]) # <--- potentials will also be at the top of the dictionary

    ###############################################################################
    #           loop through binary treatments and add data to a dictionary       #
    ###############################################################################

    for binary_treatment in binary_treatments:
        subdict = {}

        # STAR INFO. skip if just doing center of mass. 
        if binary_treatment=='CoM':
            pass
        if binary_treatment=='companions' or binary_treatment=='luminous':
            s_L = singles.star.lum * u.Lsun
            s_R = singles.star.rad * u.Rsun
            s_type = singles.star.type

            bp1_L = binaries.p1.star.lum * u.Lsun
            bp1_R = binaries.p1.star.rad * u.Rsun
            bp1_type = binaries.p1.star.type

            bp2_L = binaries.p2.star.lum * u.Lsun
            bp2_R = binaries.p2.star.rad * u.Rsun
            bp2_type = binaries.p2.star.type

            if binary_treatment=='luminous':
                b_L = np.where(luminous_mask, bp1_L, bp2_L)
                b_R = np.where(luminous_mask, bp1_R, bp2_R)
                b_type = np.where(luminous_mask, bp1_type, bp2_type)
            if binary_treatment=='companions':
                b_L = np.concatenate([bp1_L, bp2_L])
                b_R = np.concatenate([bp1_R, bp2_R])
                b_type = np.concatenate([bp1_type, bp2_type])

            ### concatenate singles/binaries and add to subdict. 
            subdict["type"] = np.concatenate([s_type, b_type])
            subdict["L"] = np.concatenate([s_L, b_L])
            subdict["R"] = np.concatenate([s_R, b_R]) 

        # STREAMFRAME COORDINATES:
        s_coords = single_coords
        if binary_treatment=="CoM":
            # bp1_coords, bp2_coords = binary_coords, binary_coords ## give bp1 and bp2 both the center of mass coords
            b_coords = binary_coords

        if binary_treatment=="companions" or binary_treatment=='luminous':
            # now i need to lookup the coordinates of all of these guys crom coords. 
            bp1_coords = {key:all_coords[key][mask_bp1] for key in all_coords.keys()} # i'm a genius lol
            bp2_coords = {key:all_coords[key][mask_bp2] for key in all_coords.keys()}

            if binary_treatment=='luminous':
                b_coords = {key:np.where(luminous_mask, bp1_coords[key], bp2_coords[key]) for key in all_coords.keys()}
            if binary_treatment=='companions':
                keys = ['phi1', 'phi2', 'pm_phi1','pm_phi2','r', 'vr']
                b_coords = {
                    key:np.concatenate([bp1_coords[key], bp2_coords[key]]) for key in keys
                }
        ## concatenate singles/binaries and add to subdict. 
        keys = ['phi1','phi2','pm_phi1','pm_phi2','r','vr']
        coords = {
            key:np.concatenate([s_coords[key], b_coords[key]]) for key in keys
        }
        subdict["coords"] = coords


        # GALACTOCENTRIC PHASE SPACE POSITIONS
        spos, svel = core_to_galcen_frame(path, singles, file_i, core=core)
        if binary_treatment=='CoM':
            bpos, bvel = core_to_galcen_frame(path, binaries, file_i, core=core)


        if binary_treatment=='companions' or binary_treatment=='luminous':
            bp1pos = allpos[mask_bp1]
            bp1vel = allvel[mask_bp1]
            bp2pos = allpos[mask_bp2]
            bp2vel = allvel[mask_bp2]

            if binary_treatment=='luminous':
                bpos = np.where(luminous_mask[:, None], bp1pos, bp2pos) # reshape the luminosity mask for position/velocity dimensions. 
                bvel = np.where(luminous_mask[:, None], bp1vel, bp2vel) # reshape the luminosity mask for position/velocity dimensions. 
            if binary_treatment=='companions':
                bpos = np.concatenate([bp1pos, bp2pos])
                bvel = np.concatenate([bp1vel, bp2vel])
        
        pos, vel = np.concatenate([spos, bpos]), np.concatenate([svel, bvel])
        subdict["pos"] = pos
        subdict["vel"] = vel


        # MASSES
        smass = singles.mass*u.Msun
        if binary_treatment=='CoM':
            # bp1mass, bp2mass = binaries.mass*u.Msun, binaries.mass*u.Msun
            bmass = binaries.mass * u.Msun
        if binary_treatment=='companions' or binary_treatment=='luminous':
            bp1mass = binaries.p1.mass * u.Msun
            bp2mass = binaries.p2.mass * u.Msun

            if binary_treatment=='luminous':
                bmass = np.where(luminous_mask, bp1mass, bp2mass)
            if binary_treatment=='companions':
                bmass = np.concatenate([bp1mass, bp2mass])

        mass = np.concatenate([smass, bmass])
        subdict['mass'] = mass


        ### straighten the stream coordinates. 
        inMW, trim = trim_coords_percentile(coords, low=1, high=99, apo=apo) # <-- do the trimming based on center of mass coordinates ? ? ? 
        subdict['inMW'] = inMW
        subdict['trim'] = trim
        sc, interp_orbit, orbit_coords, orbit_w, itr = straighten_stream_orbit_interp(
            coords, ['phi2','r','vr', 'pm_phi1','pm_phi2'], core, i, 
            trim_criteria = [inMW, trim], Dt_start=240,
            return_orbit_chunk=True, use_core=use_core, init_displacement=init_displacement, file_index=file_index
        )
        phi2_straight, r_straight, vr_straight, pm_phi1_straight, pm_phi2_straight = sc 

        subdict['phi2_straight'] = phi2_straight
        subdict['r_straight'] = r_straight
        subdict['vr_straight'] = vr_straight
        subdict['pm_phi1_straight'] = pm_phi1_straight
        subdict['pm_phi2_straight'] = pm_phi2_straight

        ##### add the data from this iteration to the giant dictionary. 
        data_dict[binary_treatment]=subdict

    return data_dict # <--- this won't include the core but like whatever ??? 



def intrinsic_stream_data_v3(path, i, core, apo, init_displacement,
                            use_core=False,
                            binary_treatments = ["CoM","companions","luminous"] # <-- "CoM" to do the analysis with center of mass values, "companions" to use the values for the more luminous companion. 
                             ): 
    """
    v3 is different from v2 because it does not rely on a simulation indexing convention with n
    instead just pass a path, init_displacement, core, apo, etc 


    load siminfo concatenate singles + binary p1 + binary p2 data. <-- so this is a reordered order. 

    notes:
        binary_treatment=options are 'CoM', 'companions', 'luminous' <--provide as list

    NOTE: I return nsingles, nbinaries so that if I just want coordinates and don't want to double count
    the binaries, I can index only up to [:nsingles+nbinaries]
    """

    file_index=int(i/10)
    
    data_dict = {} # <-- I will return this. 
    data_dict["init_displacement"] = init_displacement #<-- so i don't have to do this later... 

    #### load particle and streamframe data:
    if use_core==True: # only want to use core if the cluster is like *just* dissolved.... could probably not have split this into cases but whatever. 
        particle_data, streamframe_data = load_coords_v2(path, i, core, tdis_estimate=int(i-1), file_index=file_index,
                                                        tdis_estimate_index=int(file_index-1))
    if use_core==False:
        particle_data, streamframe_data = load_coords_v2(path, i, core=None, 
                                                         use_core=False, check_dissolved=False,
                                                         init_displacement=init_displacement, file_index=file_index)

    all_particles, singles, binaries = particle_data
    allpos, allvel = CM_to_galcen_frame(path, all_particles, file_index)
    nsingles, nbinaries = len(singles.mass), len(binaries.mass)
    ### number of single and binary stars are stored at the top of the data dictionary. 
    data_dict['nsingles'] = nsingles
    data_dict['nbinaries'] = nbinaries

    all_coords, single_coords, binary_coords = streamframe_data
    all_IDs = all_particles.id

    # Ids
    sid = singles.id
    bp1id = binaries.p1.id
    bp2id = binaries.p2.id
    luminous_mask = binaries.p1.star.lum >= binaries.p2.star.lum # <--- use np.where(luminous_mask, p1 property, p2 property) to index the property of the more luminous companion. 
    data_dict['IDs'] = np.concatenate([sid, bp1id, bp2id]) # <-- ids will be in the top level of the dictionary

    # create a lookup table to index binary p1 and p2 information in the all particles table. (rly just needed for the streamframe coordinate data.)
    lookup = {v:i for i, v in enumerate(all_IDs)}
    mask_bp1 = np.array([lookup[x] for x in bp1id])
    mask_bp2 = np.array([lookup[x] for x in bp2id])

    # external potentials
    s_pot = singles.pot_ext # pc^2/myr^2
    #### binary potential values will always just be the two values.... going to assume it's not drastically different between them for actual bound binaries. 
    bp1_pot, bp2_pot = binaries.p1.pot_ext, binaries.p2.pot_ext 
    data_dict['pot'] = np.concatenate([s_pot, bp1_pot, bp2_pot]) # <--- potentials will also be at the top of the dictionary

    ###############################################################################
    #           loop through binary treatments and add data to a dictionary       #
    ###############################################################################

    for binary_treatment in binary_treatments:
        subdict = {}

        # STAR INFO. skip if just doing center of mass. 
        if binary_treatment=='CoM':
            pass
        if binary_treatment=='companions' or binary_treatment=='luminous':
            s_L = singles.star.lum * u.Lsun
            s_R = singles.star.rad * u.Rsun
            s_type = singles.star.type

            bp1_L = binaries.p1.star.lum * u.Lsun
            bp1_R = binaries.p1.star.rad * u.Rsun
            bp1_type = binaries.p1.star.type

            bp2_L = binaries.p2.star.lum * u.Lsun
            bp2_R = binaries.p2.star.rad * u.Rsun
            bp2_type = binaries.p2.star.type

            if binary_treatment=='luminous':
                b_L = np.where(luminous_mask, bp1_L, bp2_L)
                b_R = np.where(luminous_mask, bp1_R, bp2_R)
                b_type = np.where(luminous_mask, bp1_type, bp2_type)
            if binary_treatment=='companions':
                b_L = np.concatenate([bp1_L, bp2_L])
                b_R = np.concatenate([bp1_R, bp2_R])
                b_type = np.concatenate([bp1_type, bp2_type])

            ### concatenate singles/binaries and add to subdict. 
            subdict["type"] = np.concatenate([s_type, b_type])
            subdict["L"] = np.concatenate([s_L, b_L])
            subdict["R"] = np.concatenate([s_R, b_R]) 

        # STREAMFRAME COORDINATES:
        s_coords = single_coords
        if binary_treatment=="CoM":
            # bp1_coords, bp2_coords = binary_coords, binary_coords ## give bp1 and bp2 both the center of mass coords
            b_coords = binary_coords

        if binary_treatment=="companions" or binary_treatment=='luminous':
            # now i need to lookup the coordinates of all of these guys crom coords. 
            bp1_coords = {key:all_coords[key][mask_bp1] for key in all_coords.keys()} # i'm a genius lol
            bp2_coords = {key:all_coords[key][mask_bp2] for key in all_coords.keys()}

            if binary_treatment=='luminous':
                b_coords = {key:np.where(luminous_mask, bp1_coords[key], bp2_coords[key]) for key in all_coords.keys()}
            if binary_treatment=='companions':
                keys = ['phi1', 'phi2', 'pm_phi1','pm_phi2','r', 'vr']
                b_coords = {
                    key:np.concatenate([bp1_coords[key], bp2_coords[key]]) for key in keys
                }
        ## concatenate singles/binaries and add to subdict. 
        keys = ['phi1','phi2','pm_phi1','pm_phi2','r','vr']
        coords = {
            key:np.concatenate([s_coords[key], b_coords[key]]) for key in keys
        }
        subdict["coords"] = coords


        # GALACTOCENTRIC PHASE SPACE POSITIONS
        spos, svel = core_to_galcen_frame(path, singles, file_index, core=core)
        if binary_treatment=='CoM':
            bpos, bvel = core_to_galcen_frame(path, binaries, file_index, core=core)


        if binary_treatment=='companions' or binary_treatment=='luminous':
            bp1pos = allpos[mask_bp1]
            bp1vel = allvel[mask_bp1]
            bp2pos = allpos[mask_bp2]
            bp2vel = allvel[mask_bp2]

            if binary_treatment=='luminous':
                bpos = np.where(luminous_mask[:, None], bp1pos, bp2pos) # reshape the luminosity mask for position/velocity dimensions. 
                bvel = np.where(luminous_mask[:, None], bp1vel, bp2vel) # reshape the luminosity mask for position/velocity dimensions. 
            if binary_treatment=='companions':
                bpos = np.concatenate([bp1pos, bp2pos])
                bvel = np.concatenate([bp1vel, bp2vel])
        
        pos, vel = np.concatenate([spos, bpos]), np.concatenate([svel, bvel])
        subdict["pos"] = pos
        subdict["vel"] = vel


        # MASSES
        smass = singles.mass*u.Msun
        if binary_treatment=='CoM':
            # bp1mass, bp2mass = binaries.mass*u.Msun, binaries.mass*u.Msun
            bmass = binaries.mass * u.Msun
        if binary_treatment=='companions' or binary_treatment=='luminous':
            bp1mass = binaries.p1.mass * u.Msun
            bp2mass = binaries.p2.mass * u.Msun

            if binary_treatment=='luminous':
                bmass = np.where(luminous_mask, bp1mass, bp2mass)
            if binary_treatment=='companions':
                bmass = np.concatenate([bp1mass, bp2mass])

        mass = np.concatenate([smass, bmass])
        subdict['mass'] = mass


        ### straighten the stream coordinates. 
        inMW, trim = trim_coords_percentile(coords, low=1, high=99, apo=apo) # <-- do the trimming based on center of mass coordinates ? ? ? 
        subdict['inMW'] = inMW
        subdict['trim'] = trim
        sc, interp_orbit, orbit_coords, orbit_w, itr = straighten_stream_orbit_interp(
            coords, ['phi2','r','vr', 'pm_phi1','pm_phi2'], core, i, 
            trim_criteria = [inMW, trim], Dt_start=240,
            return_orbit_chunk=True, use_core=use_core, init_displacement=init_displacement, file_index=file_index
        )
        phi2_straight, r_straight, vr_straight, pm_phi1_straight, pm_phi2_straight = sc 

        subdict['phi2_straight'] = phi2_straight
        subdict['r_straight'] = r_straight
        subdict['vr_straight'] = vr_straight
        subdict['pm_phi1_straight'] = pm_phi1_straight
        subdict['pm_phi2_straight'] = pm_phi2_straight

        ##### add the data from this iteration to the giant dictionary. 
        data_dict[binary_treatment]=subdict

    return data_dict # <--- this won't include the core but like whatever ??? 




def galcen_to_ICRS(pos, vel):
    """
    ideally pos and vel have astropy units, and shape nx3
    """
    # create a cartesian representation/differential
    rep = CartesianRepresentation(pos.T)
    rep_vel = CartesianDifferential(vel.T)
    rep = rep.with_differentials(rep_vel)

    # create coords in galactocentric frame
    galcen_frame = Galactocentric()
    coords_galcen = SkyCoord(rep, frame=galcen_frame)

    # transform to ICRS
    coords_ICRS = coords_galcen.transform_to(ICRS())
    return coords_ICRS

#-----------------------------------------------------------------------------------------#
#                                  photometry stuff                                       #
#-----------------------------------------------------------------------------------------#

def m_from_M(M, dist):
    """
    provide distance as an astropy quantity with units
    """
    m = M + (5*np.log10(dist.to(u.pc).value)) -  5
    return m

def B(nu, T):
    """
    compute a blackbody function for temperature T at frequency nu
    """
    h = const.h.cgs.value
    c = const.c.cgs.value
    k = const.k_B.cgs.value

    num = 2*h*nu**3 / c**2
    denom = np.exp(h*nu/(k*T)) - 1
    return num/denom


def define_photometric_bands():
    """
    returns gaia G, BP, RP, and (sdss?) z min/max frequencies with astropy units
    """
    ### from Gaia DR2 paper: https://www.aanda.org/articles/aa/full_html/2018/09/aa33462-18/aa33462-18.html
    lambda_G_min, lambda_G_max = 330*u.nm.to(u.micron), 1050*u.nm.to(u.micron)
    nu_G_min, nu_G_max = l_to_nu(lambda_G_max)*u.Hz, l_to_nu(lambda_G_min)*u.Hz


    lambda_BP_min, lambda_BP_max = 330*u.nm.to(u.micron), 680*u.nm.to(u.micron)
    nu_BP_min, nu_BP_max = l_to_nu(lambda_BP_max)*u.Hz, l_to_nu(lambda_BP_min)*u.Hz

    lambda_RP_min, lambda_RP_max = 630*u.nm.to(u.micron), 1050*u.nm.to(u.micron)
    nu_RP_min, nu_RP_max = l_to_nu(lambda_RP_max)*u.Hz, l_to_nu(lambda_RP_min)*u.Hz

    lambda_z = 900 * u.nm.to(u.micron)
    w_z = 100/2 * u.nm.to(u.micron)
    lambda_z_min, lambda_z_max = lambda_z - w_z, lambda_z + w_z
    nu_z_min, nu_z_max = l_to_nu(lambda_z_min)*u.Hz, l_to_nu(lambda_z_max)*u.Hz
    return nu_G_min, nu_G_max, nu_BP_min, nu_BP_max, nu_RP_min, nu_RP_max, nu_z_min, nu_z_max


def integrated_mag(nu_min, nu_max, T, R, d=10):
    """
    compute magnitude at a given frequency and stellar surface temperature/radius
    d=10 for absolute magnitude, otherwise compute with a distance
    """
    
    ### integrate over frequency 
    nu_range = np.linspace(nu_min, nu_max, 1000)

    # compute flux
    f_nu = np.pi * B(nu_range, T) ## specific flux! is pi times B_nu. 
    L_nu = f_nu * (4*np.pi*R**2) ## multiply by stellar surface area

    # adjust to 10 K Pc?
    f_fid = L_nu / (4*np.pi*(d*u.pc).cgs.value**2)

    ### now integrate this...
    f_filter = np.trapezoid(f_fid/nu_range, nu_range)
    f_filter /= np.trapezoid(1/nu_range, nu_range) ### suggestion that idk why works. 

    #### EVENTUALLY__ this should be integrated over a frequency range. 
    M = -2.5*np.log10(f_filter) - 48.60
   
    return M

def l_to_nu(l):
    """
    convert wavelength in microns to frequency in Hz
    """
    c = const.c.cgs.value
    nu = c*(1e+4)/l
    return nu




def get_gaia_photometry(Teff, Radius, distance):
    nus = define_photometric_bands()
    nu_G_min, nu_G_max, nu_BP_min, nu_BP_max, nu_RP_min, nu_RP_max, nu_z_min, nu_z_max = nus
    # frequencies = [nu_G.to(u.Hz).value, nu_BP.to(u.Hz).value, nu_RP.to(u.Hz).value]
    f_min = [nu_G_min.to(u.Hz).value, nu_BP_min.to(u.Hz).value, nu_RP_min.to(u.Hz).value]
    f_max = [nu_G_max.to(u.Hz).value, nu_BP_max.to(u.Hz).value, nu_RP_max.to(u.Hz).value]

    mags = []
    for nu_min, nu_max in zip(f_min, f_max):
        mag = integrated_mag(nu_min, nu_max, Teff, Radius, distance)
        mags.append(mag)
    return mags

def get_z_photometry(Teff, Radius, distance):
    nus = define_photometric_bands()
    nu_G_min, nu_G_max, nu_BP_min, nu_BP_max, nu_RP_min, nu_RP_max, nu_z_min, nu_z_max = nus
    f_min = nu_z_min.to(u.Hz).value
    f_max = nu_z_max.to(u.Hz).value
    mag = integrated_mag(f_min, f_max, Teff, Radius, distance)
    return mag

